### ISSUE TITLE
Null error while trying to create any UI element

### ISSUE THREAD

**Issue by edgargaza** [BattlefieldNoob/UIMaterialElements#3]
Hello there.

Maybe I'm missing something, but when I try to create any UI element, a null error is thrown because the ComponentPrefabs folder where the resource is trying to search the UI component prefabs does not exist.

I just imported this repository from the Package Manager and tried to create a MaterialUI element. Did I miss something?

Thank you in advance.

**Comment by edgargaza** [comment]
I did some updates in the package code locally and I got it to work. I replaced each "ComponentPrefabs" to "Runtime/ComponentPrefabs" of each asset path on each method from the _MaterialUIEditorTools_ static class.

**Comment by edgargaza** [comment]
I have found an other error while trying to create the Screen UI element. In the same static class previously mentioned, it has been setted "ComponentPrefabsH" instead of "ComponentPrefabs". It had to be "Runtime/ComponentPrefabs" as well, in order to work.

If you confirm these are errors, I can fix it and create a new pull request, if you want.

**Comment by BattlefieldNoob** [comment]
Hi Edgargaza,
yes you can create a pull request, i will check it asap

thank you

**Comment by BattlefieldNoob** [comment]
Pull Request merged, closing issue
